[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml"

# Redirecciones para asegurar que estos archivos se sirvan correctamente
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap*.xml"
  to = "/sitemap:splat.xml"
  status = 200
  force = true