[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
  
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-0.xml"
  to = "/sitemap-0.xml"
  status = 200
  force = true